package models

import "time"

// ElementHints captures extra selector hints carried alongside a recorded
// step (e.g. attributes, tag) that help the LLM agent re-discover the element.
type ElementHints struct {
	Attributes map[string]string `json:"attributes"`
	TagName    string            `json:"tagName"`
}

// RecordingStep is the canonical step shape stored inside both
// ManualRecording (legacy manual recorder) and AutomationTest (generated by
// the LLM agent). The Result* fields are populated after the step is run.
type RecordingStep struct {
	Action             string       `json:"action"`
	Description        string       `json:"description"`
	ElementHints       ElementHints `json:"elementHints"`
	Selector           string       `json:"selector"`
	SelectorCandidates []string     `json:"selectorCandidates"`
	XPath              string       `json:"xpath,omitempty"`
	XPathCandidates    []string     `json:"xpathCandidates,omitempty"`

	// API specific fields
	ApiMethod   string `json:"apiMethod,omitempty"`
	ApiEndpoint string `json:"apiEndpoint,omitempty"`
	ApiPayload  string `json:"apiPayload,omitempty"`
	ApiHeaders  string `json:"apiHeaders,omitempty"`

	Value         string `json:"value,omitempty"`
	AssertionType string `json:"assertionType,omitempty"`
	ExpectedValue string `json:"expectedValue,omitempty"`

	// Execution result fields (populated after running)
	ResultStatus     string `json:"resultStatus,omitempty"`
	ResultError      string `json:"resultError,omitempty"`
	ResultScreenshot string `json:"resultScreenshot,omitempty"`
}

// ManualRecording is the top-level browser-recording document stored in
// Redis. It is the legacy source of truth for manually recorded QA tests
// and is consumed by the agent tool that turns recordings into runnable
// scenarios.
type ManualRecording struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description string          `json:"description,omitempty"`
	ProjectID   string          `json:"projectId,omitempty"`
	ProjectName string          `json:"projectName,omitempty"`
	IssueID     string          `json:"issueId,omitempty"`
	TestCaseID  string          `json:"testCaseId,omitempty"`
	Status      string          `json:"status,omitempty"`
	VideoURL    string          `json:"videoUrl,omitempty"`
	Steps       []RecordingStep `json:"steps"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
	CreatorID   int             `json:"creatorId,omitempty"`
}

// TestResult captures the outcome of a single Playwright execution of a
// scenario (or chained run). The agent runner fills this in before publishing
// the terminal stream event.
type TestResult struct {
	TestID        string         `json:"testId"`
	Status        string         `json:"status"`
	Log           string         `json:"log,omitempty"`
	VideoURL      string         `json:"videoUrl,omitempty"`
	StepResults   []TestStepResult `json:"stepResults,omitempty"`
	RunDurationMs int64          `json:"runDurationMs,omitempty"`
}

// TestStepResult is the per-step breakdown recorded inside TestResult.
type TestStepResult struct {
	StepIndex  int    `json:"stepIndex"`
	Status     string `json:"status"`
	Error      string `json:"error,omitempty"`
	Screenshot string `json:"screenshot,omitempty"`
}

// GeneratedAutomation is what the LLM generation worker emits for one test
// case before it is committed via the save_automation_test tool.
type GeneratedAutomation struct {
	ID         string          `json:"id"`
	Name       string          `json:"name"`
	Framework  string          `json:"framework,omitempty"`
	RepoID     string          `json:"repoId,omitempty"`
	TestCaseID string          `json:"testCaseId,omitempty"`
	Steps      []RecordingStep `json:"steps"`
}
