package services

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"qa-extension-backend/internal/models"
	"qa-extension-backend/tracker"

	"google.golang.org/genai"
)

const APITestPromptLLMModel = "gemini-3.1-flash-lite"

// GenerateAPITestPromptWithLLM asks an LLM to convert test case context into a concise,
// actionable prompt for a backend developer's local coding agent.
func GenerateAPITestPromptWithLLM(ctx context.Context, scenario models.TestScenario, testCase models.TestCase, backendRepoID string, backendRepoName string) (string, error) {
	rawPrompt := BuildAPITestPrompt(scenario, testCase, backendRepoID, backendRepoName)
	prompt := buildAPITestPromptRefinementPrompt(rawPrompt)

	projectID := os.Getenv("GOOGLE_CLOUD_PROJECT")
	location := os.Getenv("VERTEX_LOCATION")
	if location == "" {
		location = "us-central1"
	}

	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		Backend:  genai.BackendVertexAI,
		Project:  projectID,
		Location: location,
	})
	if err != nil {
		return "", fmt.Errorf("failed to create genai client: %w", err)
	}

	config := &genai.GenerateContentConfig{
		Temperature: genai.Ptr(float32(0.15)),
	}

	llmStart := time.Now()
	resp, err := client.Models.GenerateContent(ctx, APITestPromptLLMModel, genai.Text(prompt), config)
	llmDuration := time.Since(llmStart)
	if err != nil {
		return "", fmt.Errorf("api test prompt generation failed: %w", err)
	}

	if resp != nil && resp.UsageMetadata != nil {
		tracker.Log(ctx, tracker.TokenUsage{
			Feature:      "api_test_prompt_generation",
			Model:        APITestPromptLLMModel,
			InputTokens:  resp.UsageMetadata.PromptTokenCount,
			OutputTokens: resp.UsageMetadata.CandidatesTokenCount,
			TotalTokens:  resp.UsageMetadata.TotalTokenCount,
			Duration:     llmDuration,
		})
	}

	generatedPrompt := strings.TrimSpace(getResponseString(resp))
	if generatedPrompt == "" {
		return "", fmt.Errorf("empty API test prompt generated by LLM")
	}

	return generatedPrompt, nil
}

func buildAPITestPromptRefinementPrompt(rawPrompt string) string {
	return fmt.Sprintf(`You are an expert QA prompt engineer.

Your job is to generate the final prompt that will be given to a backend developer's local AI coding agent.

Use the provided QA test case context to write a concise, specific, and actionable prompt that helps the coding agent generate strong backend API tests.

Requirements for the final prompt:
- Do NOT write the API test code yourself.
- Tell the coding agent to inspect the backend repository before making changes.
- Direct it to identify the relevant route, handler/controller, service/business logic, validation, auth/permission checks, and persistence layer.
- Preserve all test case facts: project, scenario, repo, test case ID/code/title, preconditions, steps, inputs, and expected results.
- Make the requested coverage explicit: success path, validation/failure paths, auth/permission behavior, response schema/body, status codes, and persisted side effects.
- Tell it to use the backend repo's existing test framework, factories, fixtures, helpers, and conventions.
- Tell it to avoid brittle sleeps and external dependencies.
- Tell it to run the relevant tests and fix failures.
- Keep the final prompt compact but complete. Avoid generic filler.

Return ONLY the final prompt text.

QA test case context:
%s`, rawPrompt)
}

// BuildAPITestPrompt creates a concise prompt for a backend developer's local coding agent.
func BuildAPITestPrompt(scenario models.TestScenario, testCase models.TestCase, backendRepoID string, backendRepoName string) string {
	var b strings.Builder
	b.WriteString("Generate backend API tests for the selected test case.\n\n")
	b.WriteString("Context:\n")
	b.WriteString(fmt.Sprintf("- QA project: %s\n", scenario.ProjectName))
	b.WriteString(fmt.Sprintf("- Scenario: %s\n", scenario.Title))
	b.WriteString(fmt.Sprintf("- Backend repo ID: %s\n", backendRepoID))
	if backendRepoName != "" {
		b.WriteString(fmt.Sprintf("- Backend repo: %s\n", backendRepoName))
	}
	b.WriteString("\nTest case:\n")
	b.WriteString(fmt.Sprintf("- ID: %s\n", testCase.ID))
	b.WriteString(fmt.Sprintf("- Code: %s\n", testCase.Code))
	b.WriteString(fmt.Sprintf("- Title: %s\n", testCase.Title))
	if testCase.PreCondition != "" {
		b.WriteString(fmt.Sprintf("- Preconditions:\n%s\n", indentLines(testCase.PreCondition, "  ")))
	}
	b.WriteString("\nSteps and expected results:\n")
	for _, step := range testCase.Steps {
		b.WriteString(fmt.Sprintf("%d. %s\n", step.Order, step.Action))
		if step.Data != "" {
			b.WriteString(fmt.Sprintf("   Input: %s\n", step.Data))
		}
		if step.Expected != "" {
			b.WriteString(fmt.Sprintf("   Expected: %s\n", step.Expected))
		}
	}
	b.WriteString(`
Instructions for the coding agent:
- Inspect the backend repository before writing tests.
- Identify the HTTP route, handler/controller, service, validation, auth/permission checks, and persistence layer involved.
- Create or update automated API tests using the repository's existing test framework and conventions.
- Cover success and failure paths described in the test case.
- Seed data through existing factories/fixtures/helpers; avoid brittle sleeps and external dependencies.
- Assert status codes, response body, validation messages, side effects, and permission behavior.
- Run the relevant test command and fix failures.
`)
	return strings.TrimSpace(b.String())
}

func indentLines(value string, prefix string) string {
	lines := strings.Split(strings.TrimSpace(value), "\n")
	for i := range lines {
		lines[i] = prefix + lines[i]
	}
	return strings.Join(lines, "\n")
}
