package services

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"qa-extension-backend/tracker"

	"google.golang.org/genai"
)

const DescriptionLLMModel = "gemini-3.1-flash-lite"

// GenerateScenarioDescription asks an LLM to produce a concise 1-3 sentence
// description of what a markdown-based test scenario covers.
// The content is the full markdown of the scenario file.
func GenerateScenarioDescription(ctx context.Context, title string, content string) (string, error) {
	prompt := fmt.Sprintf(`You are an expert QA engineer.

Read the following test scenario markdown and write a concise description (1-3 sentences) of what this test scenario covers.

Focus on:
- The feature, module, or functional area being tested.
- The scope of testing (e.g. CRUD operations, access control, edge cases).
- Do NOT list individual test cases.
- Do NOT include phrases like "This test scenario covers..." — just state the facts directly.

Scenario title: %s

Scenario content:
%s`, title, content)

	projectID := os.Getenv("GOOGLE_CLOUD_PROJECT")
	location := os.Getenv("VERTEX_LOCATION")
	if location == "" {
		location = "us-central1"
	}

	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		Backend:  genai.BackendVertexAI,
		Project:  projectID,
		Location: location,
	})
	if err != nil {
		return "", fmt.Errorf("failed to create genai client: %w", err)
	}

	config := &genai.GenerateContentConfig{
		Temperature: genai.Ptr(float32(0.3)),
	}

	llmStart := time.Now()
	resp, err := client.Models.GenerateContent(ctx, DescriptionLLMModel, genai.Text(prompt), config)
	llmDuration := time.Since(llmStart)
	if err != nil {
		return "", fmt.Errorf("scenario description generation failed: %w", err)
	}

	if resp != nil && resp.UsageMetadata != nil {
		tracker.Log(ctx, tracker.TokenUsage{
			Feature:      "scenario_description_generation",
			Model:        DescriptionLLMModel,
			InputTokens:  resp.UsageMetadata.PromptTokenCount,
			OutputTokens: resp.UsageMetadata.CandidatesTokenCount,
			TotalTokens:  resp.UsageMetadata.TotalTokenCount,
			Duration:     llmDuration,
		})
	}

	description := strings.TrimSpace(getResponseString(resp))
	if description == "" {
		return "", fmt.Errorf("empty description generated by LLM")
	}

	return description, nil
}
