package services

import (
	"context"
	"fmt"
	"log"
	"strings"
	"time"

	"qa-extension-backend/tracker"
)

const DescriptionLLMModel = ""

// GenerateScenarioDescription asks an LLM to produce a concise 1-3 sentence
// description of what a markdown-based test scenario covers.
// The content is the full markdown of the scenario file.
func GenerateScenarioDescription(ctx context.Context, title string, content string) (string, error) {
	log.Printf("[ScenarioDescriptionLLM] start title=%q contentBytes=%d", title, len(content))
	prompt := fmt.Sprintf(`You are an expert QA engineer.

Read the following test scenario markdown and write a concise description (1-3 sentences) of what this test scenario covers.

Focus on:
- The feature, module, or functional area being tested.
- The scope of testing (e.g. CRUD operations, access control, edge cases).
- Do NOT list individual test cases.
- Do NOT include phrases like "This test scenario covers..." — just state the facts directly.

Scenario title: %s

Scenario content:
%s`, title, content)

	llmStart := time.Now()
	resp, err := GenerateOpenAIText(ctx, OpenAILLMRequest{
		Feature:     "scenario_description_generation",
		Model:       DescriptionLLMModel,
		Prompt:      prompt,
		Temperature: 0.3,
	})
	llmDuration := time.Since(llmStart)
	if err != nil {
		log.Printf("[ScenarioDescriptionLLM] failed title=%q duration=%s error=%v", title, llmDuration, err)
		return "", fmt.Errorf("scenario description generation failed: %w", err)
	}

	if resp != nil {
		tracker.Log(ctx, tracker.TokenUsage{
			Feature:      "scenario_description_generation",
			Model:        resp.Model,
			InputTokens:  resp.InputTokens,
			OutputTokens: resp.OutputTokens,
			TotalTokens:  resp.TotalTokens,
			Duration:     llmDuration,
		})
	}

	description := strings.TrimSpace(resp.Text)
	if description == "" {
		log.Printf("[ScenarioDescriptionLLM] empty title=%q duration=%s model=%s", title, llmDuration, resp.Model)
		return "", fmt.Errorf("empty description generated by LLM")
	}

	log.Printf("[ScenarioDescriptionLLM] success title=%q model=%s duration=%s inputTokens=%d outputTokens=%d totalTokens=%d descriptionLen=%d", title, resp.Model, llmDuration, resp.InputTokens, resp.OutputTokens, resp.TotalTokens, len(description))
	return description, nil
}
